USE b12_app;
DELETE FROM quiz;
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'Who is the main female protagonist of The Vampire Diaries?', 'Elena Gilbert', 'Bonnie Bennett', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'What is the name of the town where The Vampire Diaries is set?', 'Mystic Falls', 'New Orleans', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'Which Salvatore brother is the older one?', 'Damon Salvatore', 'Stefan Salvatore', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'What supernatural creature is Bonnie Bennett?', 'A Witch', 'A Vampire', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'What is the name of the bar that Damon frequently visits?', 'Mystic Grill', 'The Bourbon Bar', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'Who is Elena Gilbert''s biological mother?', 'Isobel Flemming', 'Jenna Sommers', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'What is Stefan Salvatore''s nickname due to his dark past?', 'The Ripper', 'The Shadow', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'Who is the history teacher that becomes a vampire hunter?', 'Alaric Saltzman', 'John Gilbert', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'What type of creature is Tyler Lockwood?', 'A Werewolf', 'A Witch', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (1, 'What is the name of Elena''s younger brother?', 'Jeremy Gilbert', 'Matt Donovan', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'Who turned Stefan and Damon into vampires?', 'Katherine Pierce', 'Klaus Mikaelson', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'What is the Sun and Moon curse actually about?', 'Breaking Klaus''s hybrid curse', 'Destroying all vampires', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'Which Original vampire is known as the first hybrid?', 'Klaus Mikaelson', 'Elijah Mikaelson', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'What ring protects certain humans from supernatural death?', 'Gilbert Ring', 'Daylight Ring', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'Who is the doppelganger of Elena Gilbert from the 15th century?', 'Katherine Pierce', 'Tatia', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'What does a vampire need to walk in daylight?', 'A Daylight Ring spelled by a witch', 'A special blood potion', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'Who killed Elena''s parents by driving their car off Wickery Bridge?', 'It was an accident', 'Katherine Pierce', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'What is the name of Klaus''s sister who was daggered for 900 years?', 'Rebekah Mikaelson', 'Freya Mikaelson', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'Who sacrificed herself to bring Jeremy back to life?', 'Bonnie Bennett', 'Caroline Forbes', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (2, 'Which vampire compelled Elena to forget meeting Damon first?', 'Damon Salvatore', 'Stefan Salvatore', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'What is the name of the spell that linked all vampires to the Originals?', 'The Sireline Spell', 'The Binding Curse', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'Which character said: ''I will always choose you''?', 'Damon to Elena', 'Stefan to Caroline', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'What was the name of the dimension where dead supernatural beings go?', 'The Other Side', 'The Shadow Realm', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'Who created the first vampires using the Immortality Spell?', 'Esther Mikaelson', 'Qetsiyah', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'In which season does Bonnie become the Anchor to the Other Side?', 'Season 5', 'Season 4', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'What was the cure for vampirism hidden inside?', 'Silas''s tomb', 'The Gilbert family vault', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'Who was the first character to take the cure for vampirism?', 'Katherine Pierce', 'Elena Gilbert', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'What is the name of the ancient language used for witch spells?', 'Latin-based incantations', 'Old Norse runes', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'Who was the very first doppelganger in the Petrova bloodline?', 'Amara', 'Tatia', 1);
INSERT INTO quiz (level, ques, opt1, opt2, answer) VALUES (3, 'What did Kai Parker merge with to become the leader of the Gemini Coven?', 'His twin Luke', 'His twin Liv', 1);
